### ISSUE TITLE
More support/dev needed

### ISSUE THREAD

**Issue by mdergueche** [natecox/pyshipstation#16]
ah man, why you stopped developing this API. It is really good staring point but it lacks lots of options.

are you expecting to do some work on this library?

**Comment by natecox** [comment]
I'm not currently using the library in a project, so changes from me are probably not likely. However, I absolutely welcome suggestions and PRs and will do my best to stay active with them.

**Comment by riveramj** [comment]
@mdergueche is there something specific you needed here? I'm working on the library a bit and might be able to add your stuff.

**Comment by natecox** [comment]
Closing this issue for lack of specificity. @mdergueche if there is a specific topic that you want to suggest or need help with feel free to open a new issue.
