### ISSUE TITLE
Add settings file to allow for setting of API KEY and API SECRET during testing/development

### ISSUE THREAD

**Issue by 2ps** [natecox/pyshipstation#4]

**Comment by 2ps** [comment]
Please assign to me at your convenience

**Comment by natecox** [comment]
I'm not sure this is necessary. The best way to store the keys in a project is probably going to be based on the framework and specific needs of a given project and I don't want to make too many assumptions on use.

**Comment by natecox** [comment]
I still feel that this library shouldn't make too many assumptions regarding use, and you'd really be better off placing your keys into environment variables anyways.

Closing this, but feel free to reopen for discussion.
